apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      labels:
        app: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: greeter-server:latest
        ports:
        - containerPort: 50051
